name: Run tests

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "main"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects for test cases
        run: git lfs checkout

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        run: |

          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose build

      - name: Run unit and integration tests

        run: |
          docker compose run test
